workflows:
  remembery-app-expo-build:
    name: Remembery Expo Build
    max_build_duration: 60
    environment:
      node: 18.17.0   
      vars:
        EXPO_TOKEN: $EXPO_TOKEN
    scripts:
      - npm install
      - npx expo build:android --non-interactive
    artifacts:
      - dist/**/*.apk
