workflows:
  remembery-app-expo-build:
    name: Remembery Expo Build
    max_build_duration: 60
    environment:
      node: 18.17.0
      groups:
        - expo_credentials
    scripts:
      - npm ci
      - npm install -g eas-cli@latest
      - eas build --platform android --non-interactive --profile production
    artifacts:
      - ./dist/**/*.apk
      - ./build/**/*.apk
      - ./*.apk
